import * as path from "path";

const resPath = path.join(__dirname, "res");

export const ResourcePaths = {
  resPath,
  itemsProp: path.join(resPath, "data", "propItem.txt"),
  itemsText: path.join(resPath, "data", "propItem.txt.txt"),
  moversProp: path.join(resPath, "data", "propMover.txt"),
  moversText: path.join(resPath, "data", "propMover.txt.txt"),
  moversEx: path.join(resPath, "custom", "propMoverEx.yaml"),
  character: path.join(resPath, "custom", "characters.yaml"),
  characterText: path.join(resPath, "data", "character.txt.txt"),
  characterSchool: path.join(resPath, "custom", "characterSchool.yaml"),
  characterSchoolText: path.join(resPath, "data", "character-school.txt.txt"),
  dialogsDir: path.join(__dirname, "dialogs"),
  shopsDir: path.join(__dirname, "shops"),
  job: path.join(resPath, "custom", "job.yaml"),
  expCharacter: path.join(resPath, "custom", "expCharacter.yaml"),
  expDropLuck: path.join(resPath, "custom", "expDropLuck.yaml"),
  deathPenalty: path.join(resPath, "custom", "deathPenalty.yaml"),
  worldPath: path.join(resPath, "custom", "world.yaml"),
  world: path.join(__dirname, "maps"),
  defineWorld: path.join(resPath, "data", "defineWorld.h"),
  defineItem: path.join(resPath, "data", "defineItem.h"),
  defineItemKind: path.join(resPath, "data", "defineItemKind.h"),
  defineJob: path.join(resPath, "data", "defineJob.h"),
  defineObject: path.join(resPath, "data", "defineObj.h"),
  defineSkill: path.join(resPath, "data", "defineSkill.h"),
  defineQuest: path.join(resPath, "data", "definequest.h"),
  skillsProp: path.join(resPath, "data", "propSkill.txt"),
  skillsPropAdd: path.join(resPath, "data", "propSkillAdd.csv"),
  skillsText: path.join(resPath, "data", "propSkill.txt.txt"),
  expTablePath: path.join(resPath, "data", "expTable.inc"),
  moversPropExPath: path.join(resPath, "data", "propMoverEx.inc"),
  questsPath: path.join(__dirname, "quests"),
  questsYamlPath: path.join(__dirname, "quests-yaml"),
};
