QUEST_SCE_CAVEDISCOVERY3 = {
	title = 'IDS_PROPQUEST_SCENARIO_INC_000669',
	character = 'MaFl_SgRadion',
	end_character = 'MaHa_Ryan',
	start_requirements = {
		min_level = 121,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = 'QUEST_SCE_CAVEDISCOVERY2',
	},
	rewards = {
		gold = 0,
		exp = 1477460826,
	},
	end_conditions = {
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_SCENARIO_INC_000670',
			'IDS_PROPQUEST_SCENARIO_INC_000671',
		},
		begin_yes = {
			'IDS_PROPQUEST_SCENARIO_INC_000672',
		},
		begin_no = {
			'IDS_PROPQUEST_SCENARIO_INC_000673',
		},
		completed = {
			'IDS_PROPQUEST_SCENARIO_INC_000674',
			'IDS_PROPQUEST_SCENARIO_INC_000675',
		},
		not_finished = {
			'IDS_PROPQUEST_SCENARIO_INC_000772',
		},
	}
}
