QUEST_TUTORIAL01 = {
	title = 'IDS_PROPQUEST_INC_002191',
	character = 'MaFl_Lui',
	end_character = 'MaFl_Boboko',
	start_requirements = {
		min_level = 1,
		max_level = 5,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = '',
	},
	rewards = {
		gold = 100,
		exp = 4,
	},
	end_conditions = {
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_INC_002192',
			'IDS_PROPQUEST_INC_002193',
			'IDS_PROPQUEST_INC_002194',
			'IDS_PROPQUEST_INC_002195',
		},
		begin_yes = {
			'IDS_PROPQUEST_INC_002196',
		},
		begin_no = {
			'IDS_PROPQUEST_INC_002197',
		},
		completed = {
			'IDS_PROPQUEST_INC_002198',
		},
		not_finished = nil,
	}
}
