QUEST_SCE_QUESTIONDAILY6 = {
	title = 'IDS_PROPQUEST_SCENARIO_INC_000746',
	character = 'MaHa_Ryan',
	end_character = 'MaDa_DarMayor',
	start_requirements = {
		min_level = 121,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = 'QUEST_SCE_QUESTIONDAILY5',
	},
	rewards = {
		gold = 0,
		exp = 1641623140,
		items = {
			{ id = 'II_SYS_SYS_QUE_QUESTIONPAPER01', quantity = 1, sex = 'Any' },
		},
	},
	end_conditions = {
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_SCENARIO_INC_000747',
			'IDS_PROPQUEST_SCENARIO_INC_000748',
		},
		begin_yes = {
			'IDS_PROPQUEST_SCENARIO_INC_000749',
		},
		begin_no = {
			'IDS_PROPQUEST_SCENARIO_INC_000750',
		},
		completed = {
			'IDS_PROPQUEST_SCENARIO_INC_000752',
			'IDS_PROPQUEST_SCENARIO_INC_000753',
		},
		not_finished = {
			'IDS_PROPQUEST_SCENARIO_INC_000751',
		},
	}
}
