QUEST_SCE_CAVEDISCOVERY4 = {
	title = 'IDS_PROPQUEST_SCENARIO_INC_000678',
	character = 'MaHa_Ryan',
	end_character = 'MaHa_Ryan',
	start_requirements = {
		min_level = 121,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = 'QUEST_SCE_CAVEDISCOVERY3',
	},
	rewards = {
		gold = 0,
		exp = 1969947768,
	},
	end_conditions = {
		items = {
			{ id = 'II_SYS_SYS_QUE_THREEBOOK01', quantity = 1, sex = 'Any', remove = true },
		},
	},
	drops = {
		{ item_id = 'II_SYS_SYS_QUE_THREEBOOK01', monster_id = 'MI_SKELDEVIL', probability = '1500000000' },
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_SCENARIO_INC_000679',
			'IDS_PROPQUEST_SCENARIO_INC_000680',
			'IDS_PROPQUEST_SCENARIO_INC_000756',
		},
		begin_yes = {
			'IDS_PROPQUEST_SCENARIO_INC_000681',
		},
		begin_no = {
			'IDS_PROPQUEST_SCENARIO_INC_000683',
		},
		completed = {
			'IDS_PROPQUEST_SCENARIO_INC_000682',
			'IDS_PROPQUEST_SCENARIO_INC_000757',
		},
		not_finished = {
			'IDS_PROPQUEST_SCENARIO_INC_000684',
		},
	}
}
