QUEST_SCE_TRBHISTORY = {
	title = 'IDS_PROPQUEST_SCENARIO_INC_000394',
	character = 'MaSa_Rovanett',
	end_character = 'MaDa_Hachal',
	start_requirements = {
		min_level = 20,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = 'QUEST_SCE_VMTAM',
	},
	rewards = {
		gold = 124800,
		exp = 0,
	},
	end_conditions = {
		items = {
			{ id = 'II_SYS_SYS_QUE_BOOKTRBHIS', quantity = 1, sex = 'Any', remove = true },
		},
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_SCENARIO_INC_000395',
		},
		begin_yes = {
			'IDS_PROPQUEST_SCENARIO_INC_000396',
		},
		begin_no = {
			'IDS_PROPQUEST_SCENARIO_INC_000397',
		},
		completed = {
			'IDS_PROPQUEST_SCENARIO_INC_000398',
			'IDS_PROPQUEST_SCENARIO_INC_000399',
		},
		not_finished = {
			'IDS_PROPQUEST_SCENARIO_INC_000400',
		},
	}
}
