QUEST_SCENARIO3 = {
	title = 'IDS_PROPQUEST_SCENARIO_INC_000107',
	character = 'MaSa_Neidan',
	end_character = '',
	start_requirements = {
		min_level = 15,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = '',
	},
	rewards = {
		gold = 52000,
		exp = 0,
	},
	end_conditions = {
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_SCENARIO_INC_000108',
			'IDS_PROPQUEST_SCENARIO_INC_000109',
			'IDS_PROPQUEST_SCENARIO_INC_000110',
			'IDS_PROPQUEST_SCENARIO_INC_000111',
			'IDS_PROPQUEST_SCENARIO_INC_000112',
		},
		begin_yes = {
			'IDS_PROPQUEST_SCENARIO_INC_000113',
		},
		begin_no = {
			'IDS_PROPQUEST_SCENARIO_INC_000114',
		},
		completed = {
			'IDS_PROPQUEST_SCENARIO_INC_000115',
			'IDS_PROPQUEST_SCENARIO_INC_000116',
			'IDS_PROPQUEST_SCENARIO_INC_000117',
		},
		not_finished = {
			'IDS_PROPQUEST_SCENARIO_INC_000118',
			'IDS_PROPQUEST_SCENARIO_INC_000119',
			'IDS_PROPQUEST_SCENARIO_INC_000120',
		},
	}
}
