QUEST_JAPEVE_BOZSA = {
	title = 'IDS_PROPQUEST_INC_000642',
	character = 'MaSa_Furan',
	end_character = '',
	start_requirements = {
		min_level = 1,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR' },
		previous_quest = '',
	},
	rewards = {
		gold = 0,
		exp = 0,
		items = {
			{ id = 'II_SYS_SYS_BIN_BOZSAINT', quantity = 1, sex = 'Any' },
		},
	},
	end_conditions = {
		items = {
			{ id = 'II_SYS_SYS_QUE_GRPSAINT', quantity = 20, sex = 'Any', remove = true },
		},
	},
	drops = {
		{
			item_id = 'II_SYS_SYS_QUE_GRPSAINT',
			probability = '750000000',
			monsters = {
				'MI_WAGSAAC1',
				'MI_WAGSAAC2',
				'MI_WAGSAAC3',
				'MI_WAGSAAC4',
				'MI_MIA1',
				'MI_MIA2',
				'MI_MIA3',
				'MI_MIA4',
				'MI_MRPUMPKIN1',
				'MI_MRPUMPKIN2',
				'MI_MRPUMPKIN3',
				'MI_MRPUMPKIN4',
				'MI_REDMANTIS1',
				'MI_REDMANTIS2',
				'MI_REDMANTIS3',
				'MI_REDMANTIS4',
				'MI_JACKTHEHAMMER1',
				'MI_JACKTHEHAMMER2',
				'MI_JACKTHEHAMMER3',
				'MI_JACKTHEHAMMER4',
				'MI_GIGGLEBOX1',
				'MI_GIGGLEBOX2',
				'MI_GIGGLEBOX3',
				'MI_GIGGLEBOX4',
				'MI_ROCKMUSCLE1',
				'MI_ROCKMUSCLE2',
				'MI_ROCKMUSCLE3',
				'MI_ROCKMUSCLE4',
				'MI_HOBO1',
				'MI_HOBO2',
				'MI_HOBO3',
				'MI_HOBO4',
				'MI_DUMBBULL1',
				'MI_DUMBBULL2',
				'MI_DUMBBULL3',
				'MI_DUMBBULL4',
				'MI_TOTEMIA1',
				'MI_TOTEMIA2',
				'MI_TOTEMIA3',
				'MI_TOTEMIA4',
				'MI_CARDPUPPET1',
				'MI_CARDPUPPET2',
				'MI_CARDPUPPET3',
				'MI_CARDPUPPET4',
				'MI_TOMBSTONEBEARER1',
				'MI_TOMBSTONEBEARER2',
				'MI_TOMBSTONEBEARER3',
				'MI_TOMBSTONEBEARER4',
				'MI_BASQUE1',
				'MI_BASQUE2',
				'MI_BASQUE3',
				'MI_BASQUE4',
				'MI_PRANKSTER1',
				'MI_PRANKSTER2',
				'MI_PRANKSTER3',
				'MI_PRANKSTER4',
				'MI_WHEELEM1',
				'MI_WHEELEM2',
				'MI_WHEELEM3',
				'MI_WHEELEM4',
				'MI_SCOPICON1',
				'MI_SCOPICON2',
				'MI_SCOPICON3',
				'MI_SCOPICON4',
				'MI_FLYBAT1',
				'MI_FLYBAT2',
				'MI_FLYBAT3',
				'MI_FLYBAT4',
				'MI_BUCROW1',
				'MI_BUCROW2',
				'MI_BUCROW3',
				'MI_BUCROW4'
			}
		},
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_INC_000643',
			'IDS_PROPQUEST_INC_000644',
			'IDS_PROPQUEST_INC_000645',
			'IDS_PROPQUEST_INC_000646',
			'IDS_PROPQUEST_INC_000647',
		},
		begin_yes = {
			'IDS_PROPQUEST_INC_000648',
		},
		begin_no = {
			'IDS_PROPQUEST_INC_000649',
		},
		completed = {
			'IDS_PROPQUEST_INC_000650',
			'IDS_PROPQUEST_INC_000651',
		},
		not_finished = {
			'IDS_PROPQUEST_INC_000652',
			'IDS_PROPQUEST_INC_000653',
		},
	}
}
