QUEST_SCENARIO4 = {
	title = 'IDS_PROPQUEST_SCENARIO_INC_000197',
	character = 'MaSa_Molang',
	end_character = '',
	start_requirements = {
		min_level = 15,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = 'QUEST_SCENARIO3',
	},
	rewards = {
		gold = 2400000,
		exp = 0,
	},
	end_conditions = {
	},
	drops = {
		{ item_id = 'II_SYS_SYS_QUE_RANGLASS', monster_id = 'MI_TRANGFOMA3', probability = '1500000000' },
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_SCENARIO_INC_000198',
			'IDS_PROPQUEST_SCENARIO_INC_000199',
			'IDS_PROPQUEST_SCENARIO_INC_000200',
			'IDS_PROPQUEST_SCENARIO_INC_000201',
			'IDS_PROPQUEST_SCENARIO_INC_000202',
		},
		begin_yes = {
			'IDS_PROPQUEST_SCENARIO_INC_000203',
		},
		begin_no = {
			'IDS_PROPQUEST_SCENARIO_INC_000204',
		},
		completed = {
			'IDS_PROPQUEST_SCENARIO_INC_000205',
		},
		not_finished = nil,
	}
}
