QUEST_JAPEVE_BOZDA = {
	title = 'IDS_PROPQUEST_INC_000656',
	character = 'MaDa_Furan',
	end_character = '',
	start_requirements = {
		min_level = 1,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR' },
		previous_quest = '',
	},
	rewards = {
		gold = 0,
		exp = 0,
		items = {
			{ id = 'II_SYS_SYS_BIN_BOZDARKON', quantity = 1, sex = 'Any' },
		},
	},
	end_conditions = {
		items = {
			{ id = 'II_SYS_SYS_QUE_GRPDARKON', quantity = 20, sex = 'Any', remove = true },
		},
	},
	drops = {
		{
			item_id = 'II_SYS_SYS_QUE_GRPDARKON',
			probability = '750000000',
			monsters = {
				'MI_LEYENA1',
				'MI_LEYENA2',
				'MI_LEYENA3',
				'MI_LEYENA4',
				'MI_STEAMWALKER1',
				'MI_STEAMWALKER2',
				'MI_STEAMWALKER3',
				'MI_STEAMWALKER4',
				'MI_STEELKNIGHT1',
				'MI_STEELKNIGHT2',
				'MI_STEELKNIGHT3',
				'MI_STEELKNIGHT4',
				'MI_NUTTYWHEEL1',
				'MI_NUTTYWHEEL2',
				'MI_NUTTYWHEEL3',
				'MI_NUTTYWHEEL4',
				'MI_DRILLER1',
				'MI_DRILLER2',
				'MI_DRILLER3',
				'MI_DRILLER4',
				'MI_VOLT1',
				'MI_VOLT2',
				'MI_VOLT3',
				'MI_VOLT4',
				'MI_ELDERGUARD1',
				'MI_ELDERGUARD2',
				'MI_ELDERGUARD3',
				'MI_ELDERGUARD4',
				'MI_GARBAGEPIDER1',
				'MI_GARBAGEPIDER2',
				'MI_GARBAGEPIDER3',
				'MI_GARBAGEPIDER4',
				'MI_CRANEMACHINERY1',
				'MI_CRANEMACHINERY2',
				'MI_CRANEMACHINERY3',
				'MI_CRANEMACHINERY4',
				'MI_SYLIACA1',
				'MI_SYLIACA2',
				'MI_SYLIACA3',
				'MI_SYLIACA4',
				'MI_GREEMONG1',
				'MI_GREEMONG2',
				'MI_GREEMONG3',
				'MI_GREEMONG4',
				'MI_CARRIERBOMB1',
				'MI_CARRIERBOMB2',
				'MI_CARRIERBOMB3',
				'MI_CARRIERBOMB4',
				'MI_NUCTUVEHICLE1',
				'MI_NUCTUVEHICLE2',
				'MI_NUCTUVEHICLE3',
				'MI_NUCTUVEHICLE4',
				'MI_RISEM1',
				'MI_RISEM2',
				'MI_RISEM3',
				'MI_RISEM4',
				'MI_ZOMBIGER1',
				'MI_ZOMBIGER2',
				'MI_ZOMBIGER3',
				'MI_ZOMBIGER4',
				'MI_GRRR1',
				'MI_GRRR2',
				'MI_GRRR3',
				'MI_GRRR4',
				'MI_DUMP1',
				'MI_DUMP2',
				'MI_DUMP3',
				'MI_DUMP4',
				'MI_NAUTREPY1',
				'MI_NAUTREPY2',
				'MI_NAUTREPY3',
				'MI_NAUTREPY4',
				'MI_BOO1',
				'MI_BOO2',
				'MI_BOO3',
				'MI_BOO4',
				'MI_HOPPRE1',
				'MI_HOPPRE2',
				'MI_HOPPRE3',
				'MI_HOPPRE4',
				'MI_MUSHPOIE1',
				'MI_MUSHPOIE2',
				'MI_MUSHPOIE3',
				'MI_MUSHPOIE4',
				'MI_IREN1',
				'MI_IREN2',
				'MI_IREN3',
				'MI_IREN4',
				'MI_WATANGKA1',
				'MI_WATANGKA2',
				'MI_WATANGKA3',
				'MI_WATANGKA4',
				'MI_ANTIQUERY1',
				'MI_ANTIQUERY2',
				'MI_ANTIQUERY3',
				'MI_ANTIQUERY4',
				'MI_LUIA1',
				'MI_LUIA2',
				'MI_LUIA3',
				'MI_LUIA4',
				'MI_GONGURY1',
				'MI_GONGURY2',
				'MI_GONGURY3',
				'MI_GONGURY4',
				'MI_SHUHAMMA1',
				'MI_SHUHAMMA2',
				'MI_SHUHAMMA3',
				'MI_SHUHAMMA4',
				'MI_KERN1',
				'MI_KERN2',
				'MI_KERN3',
				'MI_KERN4',
				'MI_GLAPHAN1',
				'MI_GLAPHAN2',
				'MI_GLAPHAN3',
				'MI_GLAPHAN4',
				'MI_TRANGFOMA1',
				'MI_TRANGFOMA2',
				'MI_TRANGFOMA3',
				'MI_TRANGFOMA4'
			}
		},
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_INC_000657',
			'IDS_PROPQUEST_INC_000658',
			'IDS_PROPQUEST_INC_000659',
			'IDS_PROPQUEST_INC_000660',
			'IDS_PROPQUEST_INC_000661',
		},
		begin_yes = {
			'IDS_PROPQUEST_INC_000662',
		},
		begin_no = {
			'IDS_PROPQUEST_INC_000663',
		},
		completed = {
			'IDS_PROPQUEST_INC_000664',
			'IDS_PROPQUEST_INC_000665',
		},
		not_finished = {
			'IDS_PROPQUEST_INC_000666',
			'IDS_PROPQUEST_INC_000667',
		},
	}
}
