QUEST_SCE_HARMONINFIND = {
	title = 'IDS_PROPQUEST_SCENARIO_INC_000515',
	character = 'MaDa_DarMayor',
	end_character = 'MaDa_Esof',
	start_requirements = {
		min_level = 105,
		max_level = 129,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = 'QUEST_SCE_DAILYBOOK2',
	},
	rewards = {
		gold = 169000,
		exp = 4752893,
	},
	end_conditions = {
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_SCENARIO_INC_000516',
			'IDS_PROPQUEST_SCENARIO_INC_000517',
		},
		begin_yes = {
			'IDS_PROPQUEST_SCENARIO_INC_000518',
		},
		begin_no = {
			'IDS_PROPQUEST_SCENARIO_INC_000519',
		},
		completed = {
			'IDS_PROPQUEST_SCENARIO_INC_000520',
			'IDS_PROPQUEST_SCENARIO_INC_000521',
		},
		not_finished = {
			'IDS_PROPQUEST_SCENARIO_INC_000788',
		},
	}
}
