QUEST_LEGENDREDMANTIS1 = {
	title = 'IDS_PROPQUEST_INC_001129',
	character = 'MaFl_Rudvihil',
	end_character = 'MaSa_Helgar',
	start_requirements = {
		min_level = 60,
		max_level = 80,
		job = { 'JOB_VAGRANT', 'JOB_MERCENARY', 'JOB_ACROBAT', 'JOB_ASSIST', 'JOB_MAGICIAN', 'JOB_KNIGHT', 'JOB_BLADE', 'JOB_JESTER', 'JOB_RANGER', 'JOB_RINGMASTER', 'JOB_BILLPOSTER', 'JOB_PSYCHIKEEPER', 'JOB_ELEMENTOR', 'JOB_KNIGHT_MASTER', 'JOB_BLADE_MASTER', 'JOB_JESTER_MASTER', 'JOB_RANGER_MASTER', 'JOB_RINGMASTER_MASTER', 'JOB_BILLPOSTER_MASTER', 'JOB_PSYCHIKEEPER_MASTER', 'JOB_ELEMENTOR_MASTER', 'JOB_KNIGHT_HERO', 'JOB_BLADE_HERO', 'JOB_JESTER_HERO', 'JOB_RANGER_HERO', 'JOB_RINGMASTER_HERO', 'JOB_BILLPOSTER_HERO', 'JOB_PSYCHIKEEPER_HERO', 'JOB_ELEMENTOR_HERO' },
		previous_quest = '',
	},
	rewards = {
		gold = 0,
		exp = 1354731,
	},
	end_conditions = {
	},
	dialogs = {
		begin = {
			'IDS_PROPQUEST_INC_001130',
			'IDS_PROPQUEST_INC_001131',
			'IDS_PROPQUEST_INC_001132',
			'IDS_PROPQUEST_INC_001133',
			'IDS_PROPQUEST_INC_001134',
		},
		begin_yes = {
			'IDS_PROPQUEST_INC_001135',
		},
		begin_no = {
			'IDS_PROPQUEST_INC_001136',
		},
		completed = {
			'IDS_PROPQUEST_INC_001137',
			'IDS_PROPQUEST_INC_001138',
		},
		not_finished = {
			'IDS_PROPQUEST_INC_001139',
		},
	}
}
