server:
  host: '127.0.0.1'
  port: 23000
  build-version: '20100412'
  account-verification: true
  password-encryption-key : 'dldhsvmflvm'
  max-connection: 1000
  client-buffer-size: 128
database:
  - name: 'account'
    provider: 'sqlite' # 'sqlite' | 'mysql' | 'mssql'
    connection-string: './data/db/accounts.db'
  - name: 'game'
    provider: 'sqlite'
    connection-string: './data/db/game.db'