export enum UpdateItemType {
  UI_NUM = 0,
  UI_HP = 1,
  UI_RN = 2,
  UI_AO = 3,
  UI_RAO = 4,
  UI_IR = 5,
  UI_PIERCING_SIZE = 6,
  UI_PIERCING = 7,
  UI_COOLTIME = 8,
  UI_FLAG = 9,
  UI_RANDOMOPTITEMID = 10,
  UI_KEEPTIME = 11,
  UI_REPAIR_NUM = 12,
}
